version: '3.8'

services:
  proxy:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    command: ["python", "main.py", "--provider", "${PROVIDER}"]
    restart: unless-stopped
